spring.application.name=expense-tracker-api
server.port=${PORT:8080}

# Data source purely driven by URL. Spring will automatically extract the username and password from the postgres JDBC URL!
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:expensedb}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret
app.jwt.secret=${JWT_SECRET:94a08da1d1f5e8b7f8c09dbe9a473489849504a582c81d3ee59483325c846d0a}
app.jwt.expiration-ms=86400000
